### PR TITLE
replace recently introduced sync.WaitGroup with sync.Cond (#35)

### PR DESCRIPTION
**Pull request by rshade**
replace sync.WaitGroup with sync.Cond

This fixes a race condition caused by the invalid use of sync.WaitGroup which caused "panic: sync: WaitGroup is reused before previous Wait has returned".

### CODE REVIEW

**Comment by mporsch** [comment]
Just a heads-up about a possibly related issue that we are still investigating:

while we haven't seen any panics/crashes 🤞, we have some complaints about HTTP 506 responses from the server originating from [this code path](https://github.com/rshade/wstunnel/blob/master/tunnel/wstunsrv.go#L504-L508). I am unsure whether this is an unrelated follow-up that was previously hidden behind the panic, or a direct consequence of our fixup.

**Comment by mporsch** [comment]
Ah, got it. Please cherry-pick https://github.com/mporsch/wstunnel/commit/86d33822f6987da0af9aad78994646cbd850a29a onto this PR.

**Comment by mporsch** [comment]
Even with https://github.com/mporsch/wstunnel/commit/86d33822f6987da0af9aad78994646cbd850a29a I still think there is an issue that gets the server's tunnel stuck until the client times out and recreates it. I'll keep investigating.

**Comment by mporsch** [comment]
>server's tunnel stuck until the client times out and recreates it

Fixed with https://github.com/mporsch/wstunnel/commit/7582973929175f0bc9aceb70a1b96dfb722c7c1f

Seems to cost a bit in raw download performance. Maybe this could be improved by using go channels as hinted in https://pkg.go.dev/sync#Cond:

> For many simple use cases, users will be better off using channels than a Cond (Broadcast corresponds to closing a channel, and Signal corresponds to sending on a channel).
For more on replacements for [sync.Cond](https://pkg.go.dev/sync#Cond), see [Roberto Clapis's series on advanced concurrency patterns](https://blogtitle.github.io/categories/concurrency/), as well as [Bryan Mills's talk on concurrency patterns](https://drive.google.com/file/d/1nPdvhB0PutEJzdCq5ms6UI58dp50fcAN/view).

**Comment by rshade** [comment]
@mporsch would you mind reviewing this before I merge it, to make sure I merged it right?

**Comment by mporsch** [comment]
I verified that it contains [my initial changeset](https://github.com/mporsch/wstunnel/compare/705ae8269203398ff1ec86c806c4ba3ea5f3e892..master); so LGTM.

**Comment by rshade** [comment]
@mporsch awesome, thank you

**Pull request merged**
